[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
boss_fight_betting = "FtQbMDA7w8a9icfbMkuTxxQ695Wp9e6RQFSGVjmYQgz3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/*"
]

[test]
startup_wait = 5000

[[test.genesis]]
address = "FtQbMDA7w8a9icfbMkuTxxQ695Wp9e6RQFSGVjmYQgz3"
program = "target/deploy/boss_fight_betting.so"